### ISSUE TITLE
Fix to package file for importing

### ISSUE THREAD

**Issue by rkpatel33** [krasimir/fluxiny#3]
In the published package, I believe you should be pointing the `main` flag to the compiled min module, not the ES6 lib module. This was causing a `module not found` error for me until I manually fixed it in my node_modules folder:

```
"main": "lib/fluxiny.min.js",
```

The file pointed to here does not exist in the published module, or at least is not installed by npm:

```
"main": "src/index.js",
```

**Comment by krasimir** [comment]
Fixed. Just released `1.0.12`
